config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'signup' => 'usuarios#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'blogs' => 'blogs#index'
  get 'misblogs' => 'blogs#misblogs'
  post 'misblogs' => 'blogs#create'
  get 'blogs/new'
  root 'home#home'
  resources :usuarios
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :usuario, dependent: :destroy 
 
    validates_presence_of :titulo
    validates_presence_of :contenido

end

app/models/usuario.rb
class Usuario < ApplicationRecord
    has_secure_password
    has_many :blogs

    def autor 
        self.role == 'autor' 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    helper_method :current_user, :logged_in?

    def current_user 
        @current_user ||= Usuario.find_by(id: session[:usuario])
    end

    def logged_in?
        current_user != nil
    end   
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
 
    def index
        @blogs = Blog.all
    end

    def misblogs
        if logged_in?
            @blogs = current_user.blogs
        else
            redirect_to root_path
        end
    end

    def new
        if !logged_in?
            redirect_to login_path
        end
    end

    def show
        @blog = Blog.find(params[:id])
    end

    def create
        @blog = Blog.new(blog_params)
        @blog.usuario = current_user
        @blog.save
        redirect_to @blog
    end

    private
        def blog_params
            params.require(:blog).permit(:titulo,:contenido)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def home
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
      @usuario = Usuario.find_by_email(params[:session][:email])
      if @usuario && @usuario.authenticate(params[:session][:password])
        session[:usuario] = @usuario.id
        redirect_to '/'
      else
        redirect_to 'login'
      end 
    end

    def destroy
        session[:usuario] = nil 
        redirect_to '/' 
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController

    def new
        @usuario = Usuario.new
    end


    def create 
      @usuario = Usuario.new(user_params) 
      if @usuario.save 
        session[:usuario_id] = @usuario.id 
        redirect_to '/' 
      else 
        redirect_to '/signup' 
      end 
    end

end


private
  def user_params
    params.require(:usuario).permit(:nombre, :email, :password)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/blogs/index.html.erb
<div class = "contenedor_blogs">
    <% @blogs.each do |blog| %>
        <div class = "contenedor_lista"
            <tr>
                <div><td><b>Titulo: </b><%= blog.titulo %></td></div>
                <div><td><b>Autor: </b><%= blog.usuario.nombre %></td></div>
                <td><%= link_to 'Ver', blog_path(blog), :class => "boton_ver" %></td>
            </tr>
        </div>

    <% end %>
    <% if logged_in? %><p><%= link_to "Crear blog", blogs_new_path, :class => "boton" %></p>
    <% end %>

</div>

app/views/blogs/misblogs.html.erb
<div class = "contenedor_blogs">
    <% @blogs.each do |blog| %>
        <div class = "contenedor_lista"
            <tr>
                <div><td><b>Titulo: </b><%= blog.titulo %></td></div>
                <div><td><b>Autor: </b><%= blog.usuario.nombre %></td></div>
                <td><%= link_to 'Ver', blog_path(blog), :class => "boton_ver" %></td>
            </tr>
        </div>

    <% end %>
    <p><%= link_to "Crear blog", blogs_new_path, :class => "boton" %></p>
</div>

app/views/blogs/new.html.erb
<div class="contenedor_blogs">
  <%= form_for :blog, url: misblogs_path do |f| %>
    <p>
      <%= f.label :titulo %>
      <p><%= f.text_area :titulo %></p>
    </p>
   
    <p>
      <%= f.label :contenido %>
      <p><%= f.text_field :contenido %></p>
    </p>
   
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/blogs/show.html.erb
<div class = "contenedor_blogs">
    <tr><div><b>Titulo</b></div>
        <div><td><%= @blog.titulo %></td></div>
        <div><b>Contenido</b></div>
        <div><%= @blog.contenido %></td></div>
        <div><b>Autor: </b><%= @blog.usuario.nombre %></div>
    </tr>
    <p><%= link_to "Atras", blogs_path, :class => "boton" %></p>
</div>

app/views/home/home.html.erb
<div class = "contenedor_login">

    <p><%= link_to "Ver todos los blogs", blogs_path, :class => "boton" %></p>
    <% if logged_in? %>
        <p><%= link_to "Ver mis blogs", misblogs_path, :class => "boton" %> </p>
        <p><%= link_to "Logout", logout_path, :class => "boton", method: "delete" %> </p>
    <% else %>
        <p> <%= link_to "Log in", login_path, :class => "boton" %> </p>
        <p><%= link_to "Registrarse", signup_path, :class => "boton" %> </p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kproyecto1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usuarios/new.html.erb
<div class = "form">
    <h1>Crear cuenta</h1>
    <%= form_for(@usuario) do |f| %>
        <%= f.text_field :nombre, placeholder: "Nombre"%>
        <%= f.email_field :email, placeholder: "Correo" %>
        <%= f.password_field :password, placeholder: "Password" %>
        <%= f.submit "Crear usuario" %>
        <% end %>
</div>